#!/usr/bin/env python3
"""
Interactive setup script for the Telegram AI Bot.
Guides you through getting API keys and configuring .env
"""

import os
import sys
import re
import webbrowser
from pathlib import Path

def print_header(text):
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}\n")

def print_step(num, text):
    print(f"  {num}. {text}")

def validate_telegram_token(token):
    return bool(re.match(r'^\d+:[A-Za-z0-9_-]{27}$', token))

def validate_anthropic_key(key):
    return key.startswith('sk-ant-') and len(key) > 20

def get_telegram_token():
    print_header("🤖 Get Your Telegram Bot Token")
    print("  Visit: https://t.me/botfather\n")
    print_step(1, "Open Telegram and search for @botfather")
    print_step(2, "Send /newbot")
    print_step(3, "Choose a name and username")
    print_step(4, "Copy the token you receive\n")

    while True:
        token = input("  Paste your Telegram Bot Token: ").strip()
        if not token:
            print("  ❌ Token cannot be empty\n")
            continue
        if not validate_telegram_token(token):
            print("  ⚠️  Format looks unusual (should be: 123456:ABC-def...)")
            confirm = input("  Continue anyway? (y/n): ").strip().lower()
            if confirm == 'y':
                return token
            continue
        return token

def get_anthropic_key():
    print_header("🔑 Get Your Anthropic API Key")
    print("  Visit: https://console.anthropic.com/\n")
    print_step(1, "Sign in to your Anthropic account")
    print_step(2, "Go to 'API Keys' section")
    print_step(3, "Click 'Create Key'")
    print_step(4, "Copy the key (starts with sk-ant-)\n")

    while True:
        key = input("  Paste your Anthropic API Key: ").strip()
        if not key:
            print("  ❌ Key cannot be empty\n")
            continue
        if not validate_anthropic_key(key):
            print("  ⚠️  Key format looks unusual (should start with sk-ant-)")
            confirm = input("  Continue anyway? (y/n): ").strip().lower()
            if confirm == 'y':
                return key
            continue
        return key

def create_env_file(telegram_token, anthropic_key):
    env_content = f"""# Telegram AI Bot Configuration
# Generated by setup.py

# Required
TELEGRAM_BOT_TOKEN={telegram_token}
ANTHROPIC_API_KEY={anthropic_key}

# Optional — OpenAI key enables /gpt command
OPENAI_API_KEY=

# Optional — Telegram userbot (for accessing your personal groups)
# Get from https://my.telegram.org/apps
TELEGRAM_API_ID=
TELEGRAM_API_HASH=
TELEGRAM_PHONE=+972501234567
TELEGRAM_2FA_PASSWORD=

# Optional
ALLOWED_USER_IDS=
MAX_HISTORY_MESSAGES=40
SYSTEM_PROMPT=You are a helpful, friendly AI assistant. Answer clearly and concisely. When the user writes in Hebrew, respond in Hebrew.
"""

    env_path = Path(__file__).parent / ".env"

    if env_path.exists():
        print(f"\n  ⚠️  .env already exists")
        overwrite = input("  Overwrite? (y/n): ").strip().lower()
        if overwrite != 'y':
            print("  ❌ Setup cancelled")
            return False

    env_path.write_text(env_content)
    return True

def main():
    os.system('clear' if os.name != 'nt' else 'cls')

    print_header("Telegram AI Bot — Setup Wizard 🚀")
    print("  This script will configure your bot in 2 minutes.\n")

    try:
        # Get API keys
        telegram_token = get_telegram_token()
        anthropic_key = get_anthropic_key()

        # Confirm and create .env
        print_header("✅ Verify Your Keys")
        print(f"  Telegram Token: {telegram_token[:20]}...")
        print(f"  Anthropic Key:  {anthropic_key[:15]}...\n")

        confirm = input("  Everything looks good? (y/n): ").strip().lower()
        if confirm != 'y':
            print("  ❌ Setup cancelled\n")
            return 1

        if create_env_file(telegram_token, anthropic_key):
            print_header("✅ Setup Complete!")
            print("  Your .env file is ready.\n")
            print_step(1, "Run: python bot.py")
            print_step(2, "Send a message to your bot on Telegram")
            print_step(3, "Enjoy! 🎉\n")
            return 0
        else:
            return 1

    except KeyboardInterrupt:
        print("\n\n  ❌ Setup cancelled\n")
        return 1
    except Exception as e:
        print(f"\n  ❌ Error: {e}\n")
        return 1

if __name__ == "__main__":
    sys.exit(main())
